### ISSUE TITLE
SIBR_gaussianViewer_app.exe cannot view exported .ply files

### ISSUE THREAD

**Issue by alexeyda** [playcanvas/super-splat#3] opened 2023-10-31 20:56 UTC
When I export ply file and try to view it in SIBR_gaussianViewer_app it returns the following

```
F:\Downloads\viewers\bin\SIBR_gaussianViewer_app.exe --model-path d:\export\point_cloud.ply 

[SIBR] --  INFOS  --:   Initialization of GLFW                                                                                           
[SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 536.23[major: 4, minor: 6]                                                          
[SIBR] ##  ERROR  ##:   FILE C:\projects\gauss2\SIBR_viewers\src\projects\gaussianviewer\apps\gaussianViewer\main.cpp                                            
                                           LINE 140, FUNC main
                                           Could not find config file 'cfg_args' at d:\export\point_cloud.ply
```

**Comment by slimbuck** [comment] 2023-11-02 22:01
I tried this myself. Looks like the issue is related to additional metadata files the SIBR viewer requires (which we don't export).

**Comment by slimbuck** [comment] 2023-11-03 08:03
Closing for now. We will likely not be generating metadata for SIBR viewer.

**Closed by slimbuck** 2023-11-03 08:03 UTC
